In [2]:
import gymnasium as gym

env = gym.make("MountainCar-v0")
print(env.action_space.n)

3


In [ ]:
env = gym.make("MountainCar-v0", render_mode="human")
env.reset()

done = False
while not done:
    action = 2  # always go right!
    env.step(action)
    env.render()

In [ ]:
env.close()

In [6]:
env.reset()

(array([-0.57664335,  0.        ], dtype=float32), {})

In [9]:
env.observation_space
#a)position of car along x-axis
#b)velocity of car

Box([-1.2  -0.07], [0.6  0.07], (2,), float32)

In [10]:
print(env.observation_space.high) #max position of distance and max value of velocity
print(env.observation_space.low)

[0.6  0.07]
[-1.2  -0.07]


In [14]:
for i in range(10):
    res=env.observation_space.sample()
    print(f"{i}-th sampling gave {res}")
    

0-th sampling gave [-0.14584541 -0.00040699]
1-th sampling gave [-1.1496409  -0.02676865]
2-th sampling gave [ 0.14356829 -0.01259599]
3-th sampling gave [-0.8060011   0.04854088]
4-th sampling gave [0.45767447 0.02980704]
5-th sampling gave [-0.65645695 -0.05106874]
6-th sampling gave [-0.15417759  0.05559127]
7-th sampling gave [0.13652068 0.05053539]
8-th sampling gave [-0.9001477   0.00459586]
9-th sampling gave [-0.3804258  -0.03883722]


In [15]:
DISCRETE_OS_SIZE = [20, 20]
discrete_os_win_size = (env.observation_space.high - env.observation_space.low)/DISCRETE_OS_SIZE


print(discrete_os_win_size)

[0.09  0.007]


In [21]:
0.09*20 #is equal to [-1.2,0.6]

1.7999999999999998

In [26]:
(DISCRETE_OS_SIZE + [env.action_space.n])
#20 possible x positions
#20 possible velocity values
#3 possible actions

[20, 20, 3]

In [25]:
import numpy as np
q_table = np.random.uniform(low=-2, high=0, size=(DISCRETE_OS_SIZE + [env.action_space.n]))
type(q_table)

numpy.ndarray

In [35]:
q_table[1,:,0]

array([-1.60861576, -1.99230546, -0.5475786 , -0.24488364, -1.76268233,
       -0.74804957, -1.80335344, -1.17479384, -1.14965718, -0.26142731,
       -0.15374799, -1.2291167 , -0.45727372, -0.95646701, -1.51627929,
       -0.26489518, -0.83767714, -0.92808714, -1.06219899, -1.59688901])

In [33]:
q_table[1,:,1]

array([-0.17282989, -0.81219395, -0.8557672 , -0.39029961, -0.18526279,
       -0.73690994, -1.6790686 , -1.95992234, -1.31186072, -1.98208575,
       -0.7002224 , -1.82372897, -0.30208342, -1.64666326, -1.37740546,
       -1.40199049, -0.49540697, -1.36682079, -0.36652247, -0.87175574])